export enum DataType {
  Int,
  BigInt,
  String,
  DateTime,
  Boolean,
  Float,
  Decimal,
  Json,
  Bytes,
  Unsupported,
  Relation,
  Enum,
  Money,
}

export interface ModelProperty {
  key: string;
  type: DataType;
  gqlType: string;
  tsType: string;
  nullable: boolean;
  isArray: boolean;
  autoGenerated: boolean;
  relationName?: string;
  enumName?: string;
  unique?: boolean;
}
